#!/bin/bash
# Register the snapshot as a new AMI

# Figure out which pvGrub kernel ID we need - make sure to use the hd00 kernel since we have partitioned the root disk...
case $region in
	us-east-1)
		[ $arch = 'amd64' ] && aki="aki-499ccb20"
		[ $arch = 'i386' ] && aki="aki-659ccb0c"
	;;
	us-west-1)
		[ $arch = 'amd64' ] && aki="aki-920531d7"
		[ $arch = 'i386' ] && aki="aki-960531d3"
	;;
	us-west-2)
		[ $arch = 'amd64' ] && aki="aki-e68f11d6"
		[ $arch = 'i386' ] && aki="aki-e28f11d2"
	;;
	eu-west-1)
		[ $arch = 'amd64' ] && aki="aki-58a3452f"
		[ $arch = 'i386' ] && aki="aki-5ea34529"
	;;
	ap-southeast-1)
		[ $arch = 'amd64' ] && aki="aki-5e3e740c"
		[ $arch = 'i386' ] && aki="aki-563e7404"
	;;
	ap-southeast-2)
		[ $arch = 'amd64' ] && aki="aki-3b1d8001"
		[ $arch = 'i386' ] && aki="aki-c162fffb"
	;;
	ap-northeast-1)
		[ $arch = 'amd64' ] && aki="aki-1f6bf51e"
		[ $arch = 'i386' ] && aki="aki-196bf518"
	;;
	sa-east-1)
		[ $arch = 'amd64' ] && aki="aki-5153f44c"
		[ $arch = 'i386' ] && aki="aki-5753f44a"
	;;
	*) die "Unrecognized region:" "$region"
esac


[ $arch = 'i386' ] && ami_arch='i386'
[ $arch = 'amd64' ] && ami_arch='x86_64'

# The AMI has to start with "debian", otherwise we won't get a nice icon
# The ":N:true:standard" is necessary so that the root volume
# will be deleted on termination of the instance (specifically the "true" part)
ami_name="$distribution-$codename-$arch-$name_suffix"
log "Registering an AMI with the snapshot '$snapshot_id'"
ami_id=`euca-register \
	--name "$ami_name" --description "$description" \
	--architecture "$ami_arch" --kernel "$aki" \
	--snapshot "$snapshot_id:$volume_size:true:standard" \
	--root-device-name /dev/sda \
	| awk '{print $2}'`

# If the user has already created an unnamed AMI today,
# this will fail, so give the AMI registration command to the user
if [[ ! "$ami_id" =~ ^ami-[0-9a-z]{8}$ ]]; then
	die \
		"Unable to register an AMI." \
		"You can do it manually with:" \
		"`which euca-register` \\\\" \
		"--name '$ami_name' --description '$description' \\\\" \
		"--architecture '$ami_arch' --kernel '$aki' \\\\" \
		"--snapshot '$snapshot_id:$volume_size:true:standard' \\\\" \
		"--root-device-name /dev/sda"
fi
log "Your AMI has been created with the ID '$ami_id'"
