#!/bin/bash

# Add braintree packages
packages+=('sudo')
packages+=('ruby')
packages+=('libruby')
packages+=('ruby-shadow')
packages+=('rsync')
packages+=('less')
packages+=('apt-transport-https')
packages+=('lsb-release')
packages+=('git')
