#!/bin/bash
# Register the snapshot as a new AMI

[ $arch = 'i386' ] && ami_arch='i386'
[ $arch = 'amd64' ] && ami_arch='x86_64'

# The AMI has to start with "debian", otherwise we won't get a nice icon
# The ":N:true:standard" is necessary so that the root volume
# will be deleted on termination of the instance (specifically the "true" part)
ami_name="$distribution-$codename-$arch-$name_suffix"
log "Registering an AMI with the snapshot '$snapshot_id' using HVM"
ami_id=`euca-register \
	--name "$ami_name" --description "$description" \
	--architecture "$ami_arch" --virtualization-type hvm \
	--snapshot "$snapshot_id:$volume_size:true:gp2" \
	--root-device-name /dev/sda \
	| awk '{print $2}'`

# If the user has already created an unnamed AMI today,
# this will fail, so give the AMI registration command to the user
if [[ ! "$ami_id" =~ ^ami-[0-9a-z]{8}$ ]]; then
	die \
		"Unable to register an AMI." \
		"You can do it manually with:" \
		"`which euca-register` \\\\" \
		"--name '$ami_name' --description '$description' \\\\" \
		"--architecture '$ami_arch' --virtualization-type hvm \\\\" \
		"--snapshot '$snapshot_id:$volume_size:true:gp2' \\\\" \
		"--root-device-name /dev/sda"
fi
log "Your AMI has been created with the ID '$ami_id'"
